export const autoFishingStyles=`
.dsh-fisher-auto-section-heading{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:9px;min-height:23px}.dsh-fisher-auto-section-heading>strong{font-size:13px;letter-spacing:.07em}.dsh-fisher-auto-section-heading>small{font-size:11px;color:var(--fisher-muted)}
.dsh-fisher-auto-plan{margin:0 0 14px}.dsh-fisher-auto-goals{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.dsh-fisher .dsh-fisher-auto-goals button{position:relative;display:flex;align-items:center;gap:9px;text-align:left;min-width:0;min-height:70px;padding:10px 17px 10px 10px;background:var(--fisher-slot);border:1px solid var(--fisher-edge)}
.dsh-fisher .dsh-fisher-auto-goals button[aria-pressed=true]{background:var(--fisher-sea);border-color:var(--fisher-ink);box-shadow:inset 0 -3px color-mix(in srgb,var(--fisher-ink) 30%,transparent),2px 2px var(--fisher-shade)}
.dsh-fisher-auto-goals svg{width:27px;height:27px;flex-shrink:0}.dsh-fisher-auto-goals button>span{display:flex;flex-direction:column;gap:4px;min-width:0}.dsh-fisher-auto-goals strong{font-size:14px}.dsh-fisher-auto-goals small{font-size:10px;line-height:1.5;color:var(--fisher-muted)}.dsh-fisher-auto-goals i{position:absolute;top:3px;right:5px;font-style:normal;font-size:11px}
.dsh-fisher .dsh-fisher-auto-goal-note{font-size:11px;line-height:1.6;color:var(--fisher-muted);margin:9px 0 0}
.dsh-fisher-auto-spot{padding-top:11px;border-top:1px dashed var(--fisher-edge)}.dsh-fisher-auto-route{display:flex;align-items:center;gap:8px;min-height:32px;font-size:12px}.dsh-fisher-auto-route>svg{width:20px;height:20px;flex-shrink:0}.dsh-fisher-auto-route>.dsh-fisher-help{margin-left:auto}
.dsh-fisher-auto-spots{display:grid;grid-template-columns:1fr 1fr;gap:8px}.dsh-fisher .dsh-fisher-auto-spots button{font-size:12px;padding:8px 5px;display:flex;align-items:center;justify-content:center;gap:7px;min-width:0}.dsh-fisher .dsh-fisher-auto-spots button[aria-pressed=true]{background:var(--fisher-sea)}.dsh-fisher-auto-spots button>span{font-size:10px}
.dsh-fisher-auto-equipment{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:12px}.dsh-fisher-auto-equipment>small{font-size:11px;color:var(--fisher-muted)}.dsh-fisher .dsh-fisher-auto-equipment button{font-size:12px;padding:6px 10px}
.dsh-fisher-auto-progress{padding:12px;margin-top:14px;background:var(--fisher-raised);border:1px solid var(--fisher-edge);box-shadow:inset 3px 0 var(--fisher-gold)}.dsh-fisher-auto-progress[data-working=true]{box-shadow:inset 3px 0 #397d77}
.dsh-fisher-auto-progress .dsh-fisher-play-heading{margin:0 0 8px;gap:8px}.dsh-fisher-auto-progress .dsh-fisher-play-heading h3{font-size:13px;display:flex;align-items:center;gap:7px;line-height:1.5}.dsh-fisher-auto-progress .dsh-fisher-play-heading small{font-size:10px;white-space:nowrap}.dsh-fisher-auto-progress h3 i{width:7px;height:7px;background:var(--fisher-edge);flex-shrink:0}.dsh-fisher-auto-progress[data-working=true] h3 i{background:#397d77}
.dsh-fisher .dsh-fisher-auto-progress p{font-size:12px;line-height:1.7;margin:4px 0 9px}.dsh-fisher-auto-progress .dsh-fisher-meter-row{margin:7px 0 12px}.dsh-fisher-auto-progress .dsh-fisher-auto-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.dsh-fisher .dsh-fisher-auto-actions button{font-size:12px;padding:8px 5px}.dsh-fisher-auto-progress .dsh-fisher-quiet-actions button{font-size:11px}
.dsh-fisher .dsh-fisher-auto-history{width:100%;display:flex;align-items:center;gap:8px;padding:8px 10px;font-size:12px;margin:0 0 12px;background:var(--fisher-raised)}.dsh-fisher-auto-history svg{width:20px;height:20px}.dsh-fisher-auto-history b{margin-left:auto;font-size:10px;font-weight:500;color:var(--fisher-pink)}
@container(max-height:600px){.dsh-fisher .dsh-fisher-auto-goals button{min-height:48px;padding:8px 17px 8px 9px}.dsh-fisher-auto-goals small{display:none}.dsh-fisher-auto-plan{margin-bottom:8px}.dsh-fisher-auto-section-heading{margin-bottom:6px}.dsh-fisher-auto-spot{padding-top:8px}.dsh-fisher-auto-progress{padding:9px;margin-top:9px}.dsh-fisher-auto-history{margin-bottom:8px}}
@container(max-width:380px){.dsh-fisher-auto-goals svg{width:23px;height:23px}.dsh-fisher .dsh-fisher-auto-goals button{gap:6px;padding-left:8px}.dsh-fisher-auto-goals small{font-size:10px}}
`;
