export const uiRefinementStyles=`
.dsh-fisher-dialog .dsh-fisher-play-card:before{display:none}.dsh-fisher-dialog .dsh-fisher-toggle{font-size:max(13px,calc(var(--fisher-font,14px)*.88))}
.dsh-fisher-choice-grid[data-count="4"]{grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-fisher .dsh-fisher-search-row input{background:var(--fisher-raised);color:var(--fisher-ink);border:1px solid var(--fisher-edge);font:inherit;padding:8px}.dsh-fisher .dsh-fisher-search-row input::placeholder{color:var(--fisher-muted);opacity:1}
.dsh-fisher .dsh-fisher-check-row{font-size:max(13px,calc(var(--fisher-font,14px)*.88));line-height:1.65}.dsh-fisher-check-row span{min-width:0}.dsh-fisher .dsh-fisher-location-card[aria-pressed=true]:disabled{opacity:1}.dsh-fisher .dsh-fisher-shop-row{border-color:var(--fisher-edge)}
.dsh-fisher-inventory-search{margin:8px 0}.dsh-fisher-inventory-search select{width:100px;max-width:35%;padding:5px;font-size:12px;min-width:0;background:var(--fisher-raised);color:var(--fisher-ink);border:1px solid var(--fisher-edge)}
.dsh-fisher-settings .dsh-fisher-switch{background:var(--fisher-raised)}.dsh-fisher-settings .dsh-fisher-switch span{background:var(--fisher-muted)}.dsh-fisher-settings .dsh-fisher-switch[aria-checked=true] span,.dsh-fisher-activity-switch[aria-checked=true] .dsh-fisher-activity-switch-track i{background:var(--fisher-ink)}
.dsh-fisher-review-card{display:grid;gap:5px;padding:12px;background:var(--fisher-raised);border:1px solid var(--fisher-edge);box-shadow:inset 3px 0 var(--fisher-sea)}
.dsh-fisher-review-card small,.dsh-fisher-selected-item small{display:block;color:var(--fisher-muted);line-height:1.6}
.dsh-fisher .dsh-fisher-selected-item{width:100%;display:flex;align-items:center;gap:10px;text-align:left;padding:10px;background:var(--fisher-raised)}
.dsh-fisher-selected-item>img,.dsh-fisher-selected-item>svg{width:42px;height:42px;object-fit:contain;flex-shrink:0}.dsh-fisher-selected-item>span:nth-last-child(2){flex:1;min-width:0}.dsh-fisher-selected-item>span:last-child{flex-shrink:0;font-size:12px}.dsh-fisher-selected-item strong{display:block}
.dsh-fisher-item-picker{display:grid;gap:10px}.dsh-fisher-item-picker .dsh-fisher-search-row{margin:0;align-items:center}.dsh-fisher-item-picker .dsh-fisher-search-row input{width:0;min-width:0;flex:1;margin:0;padding:8px}.dsh-fisher-item-picker .dsh-fisher-search-row small{white-space:nowrap}.dsh-fisher-item-picker .dsh-fisher-pagination{margin:0}
.dsh-fisher-choice-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.dsh-fisher .dsh-fisher-choice-grid button{display:flex;flex-direction:column;align-items:center;gap:4px;min-width:0;padding:7px 5px;text-align:center;background:var(--fisher-slot);overflow-wrap:anywhere}.dsh-fisher-choice-grid img,.dsh-fisher-choice-placeholder{display:block;width:64px;height:64px;object-fit:contain;image-rendering:pixelated}.dsh-fisher-choice-placeholder{font-size:38px;line-height:64px;color:var(--fisher-muted)}.dsh-fisher-choice-grid strong{font-size:13px;line-height:1.5}.dsh-fisher-choice-grid small{font-size:11px;line-height:1.5;color:var(--fisher-muted)}.dsh-fisher-choice-grid em{margin-top:auto;font-style:normal;font-size:11px;color:var(--fisher-pink)}
.dsh-fisher .dsh-fisher-choice-grid button[aria-pressed=true],.dsh-fisher .dsh-fisher-outfit-options button[aria-pressed=true],.dsh-fisher .dsh-fisher-picnic-guests button[aria-pressed=true],.dsh-fisher .dsh-fisher-bait-options button[aria-pressed=true]{background:var(--fisher-sea);border-color:var(--fisher-ink);box-shadow:inset 0 -3px var(--fisher-edge),2px 2px var(--fisher-shade)}
.dsh-fisher .dsh-fisher-display-slot{display:flex;flex-direction:column;align-items:center;gap:3px;text-align:center;padding:8px}.dsh-fisher-display-slot>img,.dsh-fisher-display-slot>.dsh-fisher-vacant{width:72px;height:64px;object-fit:contain;image-rendering:pixelated;margin:0}.dsh-fisher-display-slot>strong{font-size:14px}.dsh-fisher-display-slot>small{font-size:11px;color:var(--fisher-muted)}.dsh-fisher .dsh-fisher-clear-placement{width:100%;margin-top:12px}
.dsh-fisher-decor-grid,.dsh-fisher-bait-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0}.dsh-fisher-decor-grid button,.dsh-fisher-bait-options button{display:flex;align-items:center;gap:8px;padding:8px;text-align:left;min-width:0}.dsh-fisher-decor-grid img,.dsh-fisher-bait-options img{width:40px;height:40px;object-fit:contain;image-rendering:pixelated;flex-shrink:0}.dsh-fisher-decor-grid span,.dsh-fisher-bait-options span{display:grid;gap:3px;min-width:0}.dsh-fisher-decor-grid strong,.dsh-fisher-bait-options strong{font-size:13px}.dsh-fisher-decor-grid small,.dsh-fisher-bait-options small{font-size:11px;line-height:1.5;color:var(--fisher-muted)}
.dsh-fisher-outfit-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:12px 0}.dsh-fisher-outfit-options button{display:grid;justify-items:center;gap:7px;padding:10px}.dsh-fisher-outfit-options img{width:96px;max-width:100%;height:110px;object-fit:contain}.dsh-fisher-outfit-options strong{font-size:14px}.dsh-fisher-outfit-options small{font-size:12px;color:var(--fisher-muted)}
.dsh-fisher-picnic-guests{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dsh-fisher-picnic-guests button{display:flex;align-items:center;justify-content:center;gap:8px;padding:6px}.dsh-fisher-picnic-guests img{width:44px;height:48px;object-fit:contain}.dsh-fisher-picnic-choices fieldset{display:grid;gap:6px;border:1px solid var(--fisher-edge);padding:8px;margin:0;min-width:0}.dsh-fisher-picnic-choices legend{font-size:12px;color:var(--fisher-muted)}.dsh-fisher-picnic-choices button{padding:7px 3px}.dsh-fisher .dsh-fisher-picnic-choices button[aria-pressed=true]{background:var(--fisher-sea)}
.dsh-fisher-storage{display:grid;gap:12px}.dsh-fisher-save-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:6px 0 0;text-align:center}.dsh-fisher-save-stats dt{font-size:11px;color:var(--fisher-muted)}.dsh-fisher-save-stats dd{margin:0;font-size:20px;line-height:1.6;overflow-wrap:anywhere}.dsh-fisher-storage>small{margin-top:-8px;color:var(--fisher-muted)}.dsh-fisher-storage-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.dsh-fisher-storage-options button{display:grid;gap:6px;text-align:left;padding:12px 9px}.dsh-fisher-storage-options strong{font-size:14px}.dsh-fisher-storage-options small{font-size:11px;color:var(--fisher-muted)}.dsh-fisher-storage-reset{border-top:1px dashed var(--fisher-edge);padding-top:12px;color:var(--fisher-muted)}.dsh-fisher-storage-reset summary{cursor:pointer;font-size:12px;padding:5px 0}.dsh-fisher-storage-reset p{font-size:12px}.dsh-fisher-storage-reset button{color:var(--fisher-pink)}
.dsh-fisher-save-compare{width:100%;border-collapse:collapse;font-size:14px;margin-bottom:14px}.dsh-fisher-save-compare caption{text-align:left;margin-bottom:8px;font-weight:bold}.dsh-fisher-save-compare th,.dsh-fisher-save-compare td{padding:8px 6px;border:1px solid var(--fisher-edge);text-align:center;overflow-wrap:anywhere}.dsh-fisher-save-compare thead,.dsh-fisher-save-compare td:last-child{background:var(--fisher-raised)}
.dsh-fisher-empty-note{padding:14px;background:var(--fisher-raised);border:1px dashed var(--fisher-edge);color:var(--fisher-muted);text-align:center;line-height:1.7}.dsh-fisher-filter-status{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0}.dsh-fisher-filter-status button{font-size:12px;padding:5px 8px}
.dsh-fisher-settings-tabs,.dsh-fisher-settings-options{display:flex;gap:8px;margin:14px 0}.dsh-fisher-settings-tabs button,.dsh-fisher-settings-options button{flex:1;min-width:0;padding:9px 5px;font-size:13px}.dsh-fisher-settings-options small{display:block;margin-top:4px;color:var(--fisher-muted)}.dsh-fisher-settings-page{padding:0 0 3px;min-width:0}.dsh-fisher-settings-page>.dsh-fisher-setting-row{margin:12px 0;gap:8px}.dsh-fisher-settings-page>.dsh-fisher-setting-row button{font-size:13px;padding:8px}.dsh-fisher-settings-page>small{display:block;font-size:12px;line-height:1.7;color:var(--fisher-muted)}
.dsh-fisher-preference-row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 0;border-top:1px dashed var(--fisher-edge)}.dsh-fisher-preference-row>span{display:grid;gap:4px}.dsh-fisher-preference-row strong{font-size:14px}.dsh-fisher-preference-row small{color:var(--fisher-muted);font-size:12px;line-height:1.6}.dsh-fisher-settings .dsh-fisher-switch{border-radius:0;height:28px;min-height:28px;min-width:48px}.dsh-fisher-settings .dsh-fisher-switch span{border-radius:0}.dsh-fisher-settings .dsh-fisher-dimensions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.dsh-fisher-dimensions label{min-width:0}.dsh-fisher-settings .dsh-fisher-dimensions input{width:100%;min-width:0}.dsh-fisher-settings .dsh-fisher-volume{display:flex;flex-wrap:wrap;justify-content:space-between;padding:12px 0}.dsh-fisher-settings .dsh-fisher-volume input{width:100%;accent-color:var(--fisher-pink)}.dsh-fisher-settings .dsh-fisher-setting-sample{padding:12px;background:var(--fisher-raised);border:1px solid var(--fisher-edge);color:var(--fisher-ink);margin:10px 0}.dsh-fisher-settings .dsh-fisher-plugin-setting{margin-bottom:12px;padding-bottom:12px}
.dsh-fisher .dsh-fisher-shore-tabs button[aria-pressed=true],.dsh-fisher .dsh-fisher-spot-picker button[aria-pressed=true],.dsh-fisher .dsh-fisher-story-routes button[aria-pressed=true],.dsh-fisher .dsh-fisher-donation-list button[aria-pressed=true],.dsh-fisher .dsh-fisher-companion-options button[aria-pressed=true]{background:var(--fisher-sea)}.dsh-fisher-shore-next{background:var(--fisher-raised);border-left:3px solid var(--fisher-sea);color:var(--fisher-ink)}
@container(max-height:560px){.dsh-fisher-choice-grid img,.dsh-fisher-choice-placeholder{width:44px;height:44px}.dsh-fisher-display-slot>img,.dsh-fisher-display-slot>.dsh-fisher-vacant{height:42px}.dsh-fisher .dsh-fisher-display-slot{padding:5px}.dsh-fisher-picnic-guests img{width:30px;height:32px}.dsh-fisher-outfit-options img{height:80px}.dsh-fisher-review-card{padding:8px}.dsh-fisher .dsh-fisher-auto-goals small{display:block}.dsh-fisher-storage{gap:9px}}
@container(max-width:360px){.dsh-fisher-choice-grid{gap:6px}.dsh-fisher-choice-grid img{width:52px;height:52px}.dsh-fisher-choice-grid strong{font-size:12px}.dsh-fisher-decor-grid img,.dsh-fisher-bait-options img{width:30px;height:30px}.dsh-fisher-selected-item>img,.dsh-fisher-selected-item>svg{width:32px;height:32px}.dsh-fisher-settings-tabs{gap:5px}.dsh-fisher-settings-tabs button{font-size:12px}.dsh-fisher-save-stats dd{font-size:17px}}
`;
