export const workSupplyStyles=`
.dsh-fisher-supply-stock{padding:12px;border:1px solid var(--fisher-edge);background:var(--fisher-raised);box-shadow:inset 3px 0 var(--fisher-sea);margin-bottom:12px}
.dsh-fisher-supply-stock[data-capped=true]{box-shadow:inset 3px 0 var(--fisher-gold)}
.dsh-fisher-supply-summary{display:flex;align-items:center;gap:16px}.dsh-fisher-supply-packs{display:flex;gap:8px;align-items:center;padding-right:14px;border-right:1px dashed var(--fisher-edge);flex-shrink:0}
.dsh-fisher-supply-packs>svg{width:30px;height:30px}.dsh-fisher-supply-packs>div{display:flex;flex-direction:column;gap:3px}.dsh-fisher-supply-packs strong{font:28px ui-monospace,monospace;line-height:1.1}.dsh-fisher-supply-packs strong small{font-size:12px;color:var(--fisher-muted)}.dsh-fisher-supply-packs span{font-size:11px;color:var(--fisher-muted)}
.dsh-fisher-supply-footprints{flex:1;min-width:0}.dsh-fisher-supply-footprints>div:first-child{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:7px;font-size:12px}.dsh-fisher-supply-footprints span{font-size:11px;white-space:nowrap}.dsh-fisher-supply-footprints .dsh-fisher-meter{height:9px;border-color:var(--fisher-edge)}.dsh-fisher-supply-footprints .dsh-fisher-meter i{background:#719b85}.dsh-fisher-supply-footprints>small{display:block;font-size:10px;color:var(--fisher-muted);margin-top:6px}
.dsh-fisher .dsh-fisher-supply-stock p{font-size:11px;line-height:1.6;color:var(--fisher-muted);margin:9px 0 0}
.dsh-fisher-supply-rewards{display:flex;justify-content:space-between;gap:8px;padding:2px 0 12px;border-bottom:1px dashed var(--fisher-edge);font-size:11px}.dsh-fisher-supply-rewards>span{display:flex;align-items:center;gap:4px;white-space:nowrap}.dsh-fisher-supply-rewards svg{width:20px;height:20px}
.dsh-fisher-supply-choice{margin:12px 0 16px}.dsh-fisher-supply-heading{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:9px;min-height:23px}.dsh-fisher-supply-heading>strong{font-size:13px;letter-spacing:.05em}
.dsh-fisher-supply-baits{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px}.dsh-fisher .dsh-fisher-supply-baits button{position:relative;display:flex;flex-direction:column;align-items:center;gap:4px;min-width:0;padding:9px 3px 6px;background:var(--fisher-slot)}.dsh-fisher .dsh-fisher-supply-baits button[aria-pressed=true]{background:var(--fisher-sea);border-color:var(--fisher-ink);box-shadow:inset 0 -3px #719b85,2px 2px var(--fisher-shade)}.dsh-fisher-supply-baits img{width:42px;height:42px;object-fit:contain;image-rendering:pixelated}.dsh-fisher-supply-baits span{font-size:11px;white-space:nowrap}.dsh-fisher-supply-baits i{position:absolute;top:2px;right:4px;font-size:10px;font-style:normal;color:var(--fisher-muted)}
.dsh-fisher .dsh-fisher-supply-claim{width:100%;display:flex;align-items:center;justify-content:center;gap:9px;min-height:46px;padding:10px;background:var(--fisher-sea)}.dsh-fisher-supply-claim>svg{width:23px;height:23px}.dsh-fisher-supply-claim strong{font-size:14px}.dsh-fisher-supply-claim small{font-size:11px;font-weight:normal}.dsh-fisher .dsh-fisher-supply-full{font-size:11px;line-height:1.6;margin:8px 0 0;color:var(--fisher-muted)}
@container(max-width:400px){.dsh-fisher-supply-summary{gap:10px}.dsh-fisher-supply-packs{padding-right:10px}.dsh-fisher-supply-packs>svg{display:none}.dsh-fisher-supply-footprints>div:first-child{font-size:11px;gap:4px}.dsh-fisher-supply-baits{gap:5px}.dsh-fisher-supply-baits img{width:34px;height:34px}.dsh-fisher-supply-rewards{font-size:10px;gap:5px}.dsh-fisher-supply-rewards>span{gap:3px}.dsh-fisher-supply-rewards svg{width:16px;height:16px}}
@container(max-height:600px){.dsh-fisher-supply-stock{padding:8px;margin-bottom:8px}.dsh-fisher-supply-packs strong{font-size:24px}.dsh-fisher .dsh-fisher-supply-stock p{margin-top:6px}.dsh-fisher-supply-rewards{padding-bottom:6px}.dsh-fisher-supply-choice{margin:6px 0 8px}.dsh-fisher-supply-heading{margin-bottom:4px}.dsh-fisher .dsh-fisher-supply-baits button{padding:7px 2px 5px;gap:2px}.dsh-fisher-supply-baits img{width:32px;height:32px}.dsh-fisher .dsh-fisher-supply-claim{min-height:40px;padding:7px}}
`;
